### ISSUE TITLE
Negative linear pretrend

### ISSUE THREAD

**Issue by Alalalalaki** [mcaceresb/stata-pretrends#3]
Thank you very much for creating package.

My question is that in my practice, it seems that the generated linear pretrends at 50% or 80% are always upward-slopping curves. For those cases where the treatment effect is negative, shouldn't it be more reasonable to test a downward-slopping pretrend? Please correct me if I am wrong. Thanks!

**Comment by jonathandroth** [comment]
`pretrends power` reports the *magnitude *of the slope of a linear trend
for which power is 50%, so it is always positive by construction.

When visualizing hypothesized violations of trends, you can change the sign
of the slope if that is appropriate in your context.
