### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jonathandroth** [mcaceresb/stata-pretrends#5]
Hey Mauricio, 

I updated the pretrends R package README to give more explanations (in response to many emails I've received...): https://github.com/jonathandroth/pretrends/commit/122731d082a5990e274f57fd9af0968e44977e7a

Would you be able to update the stata-pretrends readme accordingly? 

Thanks!

**Comment by mcaceresb** [comment]
Copied the README changes (with some minor mods to adapt to the way the Stata function works) based on [this diff](https://github.com/jonathandroth/pretrends/commit/122731d082a5990e274f57fd9af0968e44977e7a).
